baseurl = "https://key-project.org/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "KeY Project"
canonifyurls  = true

DefaultContentLanguage = "en"
#theme = "beautifulhugo"
#theme = "slick"
#theme = "ananke"
#theme = "hugo-bootstrap-5"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"


[permalinks]
  news = '/:year/:month/:title/'


[Params]
  subtitle = "Deductive Verification for Java Programs"
  #text_color = "green"
  site_logo = "img/favicon.png"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = false
  #  gcse = "012345678901234567890:abcdefghijk"
  # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"


[[cascade]]
show_sidebar = true
[cascade._target]
  kind = '*'
  lang = 'en'
  path = '/news/**'
[[cascade]]
show_sidebar = true
[cascade._target]
  kind = '*'
  lang = 'en'
  path = '/news'



[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
    [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2


[Author]
   name = "KeY Team"
   email = "webmaster@key-project.org"
#   facebook = "username"
#   googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
#   gitlab = "username"
#   github = "username"
#   twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   keybase = "username"


[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 1

[[menu.main]]
    identifier="learn"
    name = "Learn"
    url = "/learn/"
    weight = 5

# [[menu.main]]
#     parent="learn"
#     name = "Documentation"
#     url = "https://key-project.org/docs/"
#     weight = 90



[[menu.main]]
    name = "Applications"
    url = "/applications/"
    weight = 10

[[menu.main]]
    name = "Download"
    url = "/download/"
    weight = 20


#[[menu.main]]
#    name = "KeY Book"
#    url = "/thebook2/"
#    weight = 50

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 70

[[menu.main]]
    identifier="about"
    name = "About"
    url = "/about/"
    weight = 100

# [[menu.main]]
#     parent = "about"
#     name = "Poeple"
#     url = "/about/people/"
#     weight = 1
