baseurl = "https://key-project.org/hugo/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "KeY Project"
canonifyurls  = true

DefaultContentLanguage = "en"
#theme = "beautifulhugo"
#theme = "slick"
theme = "ananke"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Deductive Verification for Java Programs"
  #text_color = "green"
  site_logo = "img/favicon.png"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = false
  #  gcse = "012345678901234567890:abcdefghijk"
  # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[aParams.ananke_socials]
   name= "github"
    url="https://github.com/theNewDynamic"
    label="TND GitHub Account"
    color='#ff6800'


#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[Author]
   name = "KeY Team"
   email = "webmaster@key-project.org"
#   facebook = "username"
#   googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
#   gitlab = "username"
#   github = "username"
#   twitter = "username"
#   reddit = "username"
#   linkedin = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   keybase = "username"


[[menu.main]]
    name = "News"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Learn"
    url = "/learn/"
    weight = 5

[[menu.main]]
    name = "Applications"
    url = "/applications/"
    weight = 10

[[menu.main]]
    name = "Download"
    url = "/download/"
    weight = 20


#[[menu.main]]
#    name = "KeY Book"
#    url = "/thebook2/"
#    weight = 50

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 70

[[menu.main]]
    name = "Documentation"
    url = "https://key-project.org/docs/"
    weight = 90

[[menu.main]]
    identifier="about"
    name = "About"
    url = "/about/"
    weight = 100

[[menu.main]]
    parent = "about"
    name = "Poeple"
    url = "/about/people/"
    weight = 1


# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1

# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3

# [[menu.main]]
#     name = "Tags"
#     url = "tags"
#     weight = 3
