baseURL = "http://example.org/"
languageCode = "en-us"
title = "KeY-project"
theme = "ananke"
menu = "main"
# SectionPagesMenu = "main"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "KeY Project"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3


[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
