baseURL = "http://example.org/"
languageCode = "en-us"
title = "The KeY Project"
theme = "slick"
#menu = "main"
# SectionPagesMenu = "main"

defaultContentLanguage = "en"

# Will appear below the footer links with a © sign and the current year
copyright = "Some Author — All rights reserved."




[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
                unsafe = true               # Allow html (needed for some shortcodes)
    [markup.highlight]
        codeFences = true               # Enable highlighting inside codefences
        guessSyntax = true              # Highlight code without language tag
        noClasses = false               # Use the theme's style sheet


canonifyURLs = true
preserveTaxonomyNames = true

# Configure pagination
paginate = 10
paginatePath = "page"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "KeY Project"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
    # Site subtitle (not shown if commented out or set to false)
    subtitle = "Just another site"

    # Custom css file (relative to baseURL - place below static or assets folder)
    css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateFmt = "Mon, 02 Jan 2006 15:04:05 MST"

    # Customize the text of the 404 page here
    errorPageText = "There's nothing to see here, please move along!"

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = true

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = true

    # If false the title, dates and taxonomy are not shown on single view
    showMeta = true

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false


# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"


[author]
    name = "Some Author"
    email = "mail@example.org"


[services.rss]
    # limit the length of the rss feed (default: unlimited)
    limit = 0


[menu]
    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts

    [[menu.main]]
        name = "Getting Started & Support"
        url = "/getting-started/"
        weight = 1

    [[menu.main]]
        name = "News"
        title = "News"
        url = "/posts/"
        weight = 50

    [[menu.main]]
        name = "Applications"
        url = "/applications/"
        weight = 60

    [[menu.main]]
        name = "The KeY Book"
        url = "/thebook2/"
        weight = 70

    [[menu.main]]
        name = "Publications"
        url = "/publications/"
        weight = 80

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 90

    [[menu.main]]
        name = "Download"
        url = "/download/"
        weight = 100


    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    [[menu.meta]]
        identifier = "categories"
        name = "Categories"
        weight = 1
    [[menu.meta]]
        identifier = "series"
        name = "Series"
        weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Theme repository"
        url = "https://github.com/spookey/slick"
        weight = 1

    [[menu.footer]]
        name = "Slick"
        title = "Theme page on gohugo.io"
        url = "https://themes.gohugo.io/slick"
        weight = 2

    [[menu.footer]]
        name = "Toor"
        title = "Some website, using this theme"
        url = "https://www.toor.su"
        weight = 3